const SET_EMPLOYEES = "SET_EMPLOYEES";
const SORT_EMPLOYEES = "GET_EMPLOYEES";
const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";
const RESET_SEARCH = "RESET_SEARCH";

export {
    SET_EMPLOYEES,
    SORT_EMPLOYEES,
    SEARCH_EMPLOYEES,
    RESET_SEARCH
}